version: "3.3"
services:
  file-backup:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - $DESTINATION:/var/destination
        - $SOURCE:/var/source
        - ./data/tmp:/var/tmp
    ports:
        - 127.0.0.1:18080:18080
    environment:
        - SCHEDULE
        - NAME
